# Site settings
title: Matteo Mancini, gardening experiment blog
email:
description: A blog about my gardening experience

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
imgurl: "/assets/img/"
imgurl-proj: "/assets/img/projects/"
url: "https://www.mancinimatteo.com" # the base hostname & protocol for your site

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
# data-ad-slot: 2973388149
# data-ad-client: ca-pub-9204963049240271
# google_ad_client: ca-pub-9204963049240271

google_analytics: "UA-86331249-1"
addthis_id: ra-5644da281510c62f
disqus_account: jeky-new-age

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: twitter
    url: https://twitter.com/lantoniotrento
  - title: facebook
    url: https://facebook.com/lantoniotrento
  - title: google-plus
    url: https://plus.google.com/+AntoniotrentoIt
  #- title: github
  #  url: http://github.com/jekyll

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title
#permalink:  /:title/
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
include: ["_pages"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings

# Collection definitions and settings
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Page generation
page_gen-dirs: true # uncomment, if you prefer to generate named folders
page_gen:
  - data: 'plants'
    template: 'plant' # si trova all'interno di _layout
    name: 'full_name'
    dir: 'plants'